name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

  test:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v4

      - name: Test index.js
        env:
          INPUT_GITHUB_USERNAME: "dannicraft"
          INPUT_GITHUB_TOKEN: ${{ secrets.ACTIONSECRET_DANNICRAFT }}
          INPUT_TARGET_REPOS: '["dannicraft/activity-log"]'
          INPUT_OUTPUT_STYLE: MARKDOWN
          INPUT_IGNORE_EVENTS: '[]'
          INPUT_README_PATH: README.md
          INPUT_COMMIT_MESSAGE: "Update README.md"
          INPUT_EVENT_LIMIT: '100'
        run: node ./dist/index.js
