name: GitHub Activity Log
description: Displays your GitHub activity in a README file.

inputs:
  GITHUB_USERNAME:
    description:  Your GitHub username.
    required: true
  GITHUB_TOKEN:
    description:  Your GitHub token.
    required: true
  EVENT_LIMIT:
    description:  The maximum number of events to display.
    default:  '10'
  OUTPUT_STYLE:
    description:  Specifies the format in which the output should be rendered (MARKDOWN or HTML).
    default:  MARKDOWN
  IGNORE_EVENTS:
    description:  The events to ignore, specified as a JSON array.
    required: false
    default:  '[]'
  HIDE_DETAILS_ON_PRIVATE_REPOS:
    description:  Hide details (branch/tag name) on private repositories
    required: false
    default:  'false'
  README_PATH:
    description:  The path to the README file.
    required: false
    default:  README.md
  COMMIT_MESSAGE:
    description:  Commit Message
    required: false
    default:  Update README.md with latest activity
  EVENT_EMOJI_MAP:
    description: |
      Optional YAML object mapping event types to emojis.
      Example (YAML):
        PushEvent: "🚀"
        CreateEvent: "✨"
        DeleteEvent: "🔥"
        IssuesEvent: |
          opened: "🆕"
    required: false
    default: ""
  DRY_RUN:
    description: Enable dry run mode (no changes will be committed)
    required: false
    default: 'false'
  OUTPUT_MODE:
    description: 'Output format for the activity log (list, table, or svg). When set to svg, generates an SVG image file instead of updating README directly.'
    required: false
    default: 'list'
branding:
  color: red
  icon: activity

runs:
  using:  node20
  main:  ./dist/index.js
