name: GitHub Activity Log
description: Displays your GitHub activity in a README file.

inputs:
  GITHUB_USERNAME:
    description:  Your GitHub username.
    required: true
  GITHUB_TOKEN:
    description:  Your GitHub token.
    required: true
  EVENT_LIMIT:
    description:  The maximum number of events to display.
    default:  '10'
  OUTPUT_STYLE:
    description:  Specifies the format in which the output should be rendered (MARKDOWN or HTML).
    default:  MARKDOWN
  IGNORE_EVENTS:
    description:  The events to ignore, specified as a JSON array.
    required: false
    default:  '[]'
  HIDE_DETAILS_ON_PRIVATE_REPOS:
    description:  Hide details (branch/tag name) on private repositories
    required: false
    default:  'false'
  README_PATH:
    description:  The path to the README file.
    required: false
    default:  README.md
  COMMIT_MESSAGE:
    description:  Commit Message
    required: false
    default:  Update README.md with latest activity
  EVENT_EMOJI_MAP:
    description: |
      Optional YAML object mapping event types to emojis.
      Example (YAML):
        PushEvent: "🚀"
        CreateEvent: "✨"
        DeleteEvent: "🔥"
        IssuesEvent: |
          opened: "🆕"
    required: false
    default: ""
  DRY_RUN:
    description: Enable dry run mode (no changes will be committed)
    required: false
    default: 'false'
  EVENT_TEMPLATE:
    description: |
      Custom template for event formatting. Supports placeholders:
      {icon} - Event emoji/icon
      {action} - Event action (e.g., opened, closed, committed)
      {repo} - Repository name
      {repo_url} - Repository URL
      {date} - Event date
      {number} - Issue/PR number (if applicable)
      {url} - Direct URL to the event (if applicable)
      {ref} - Branch/tag name (if applicable)
      {ref_type} - Type of ref (branch, tag, etc.)
      Example: "[{icon}] {action} {repo} on {date}"
    required: false
    default: ""
branding:
  color: red
  icon: activity

runs:
  using:  node20
  main:  ./dist/index.js
