name:  README Activity Update
description:  Updates the GitHub activity in the README file.

inputs:
  GITHUB_USERNAME:
    description:  Your GitHub username.
    required: true
  GITHUB_TOKEN:
    description:  Your GitHub token.
    required: true
  EVENT_LIMIT:
    description:  The maximum number of events to display.
    default:  '10'
  OUTPUT_STYLE:
    description:  Specifies the format in which the output should be rendered (MARKDOWN or HTML).
    default:  MARKDOWN
  IGNORE_EVENTS:
    description:  The events to ignore, specified as a JSON array.
    required: false
    default:  '[]'
  README_PATH:
    description:  The path to the README file.
    required: false
    default:  README.md
  COMMIT_MESSAGE:
    description:  Commit Message
    required: false
    default:  Update README.md with latest activity
branding:
  color: red
  icon: activity

runs:
  using:  node20
  main:  ./dist/index.js
