name: A5 - Build · Test (Node + Python) · Release

on:
  workflow_dispatch:
  push:
    branches: [ master, main, a5-test-pipeline ]

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create zip artifact
        run: zip -r app-${{ github.sha }}.zip . -x ".git/*"
      - uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: app-${{ github.sha }}.zip
          if-no-files-found: error

  test_python:
    name: Python Tests
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 安裝 Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 安裝 pytest
      - name: Install pytest
        run: |
          python -m pip install --upgrade pip
          pip install pytest

      # 執行測試
      - name: Run pytest
        run: |
          echo "Running Python tests..."
          pytest -v tests/

  release:
    name: Release (only if tests pass)
    needs: test_python
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: build-artifact
          path: .
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: a5-python-${{ github.run_number }}
          name: "A5 Python Release ${{ github.run_number }}"
          files: app-${{ github.sha }}.zip
          make_latest: false
